theme = "material_palenight"

[editor]
bufferline = "always"
auto-format = true
true-color = true
# mouse = false
line-number = "relative"
completion-timeout = 5
popup-border = 'all'

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type",  "version-control"]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false


[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
C-s = ":w!"
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E '/home/vadmas/go/bin/lazygit'"
C-w = ":buffer-close"
C-a = ":reload-all"
# y = [":clipboard-yank","yank"]
C-v = [":clipboard-paste-before"]
C-right = [":bn"]
C-left = [":bp"]
X = ["extend_line_up", "extend_to_line_bounds"]
# make sure there is only one selection, select word under cursor, set search to selection, then switch to select mode
"C-d" = ["keep_primary_selection", "move_prev_word_start", "move_next_word_end", "search_selection", "select_mode"]
# https://www.reddit.com/r/HelixEditor/comments/10reh4p/post_your_best_tipstricks_workflow_hacks_and/
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
# D = ["ensure_selections_forward", "extend_to_line_end"]
x = "extend_line"
A-right = "move_next_word_start"
A-left = "move_prev_word_start"
S-right = "extend_char_right"
S-left = "extend_char_left"
S-A-right = "extend_next_word_start"
S-A-left = "extend_prev_word_start"
S-up = "extend_line_up"
S-down = "extend_line_down"
C-S-up = "copy_selection_on_prev_line"
C-S-down = "copy_selection_on_next_line"
C-t = [":new", ":insert-output fzf-helix", ":theme default", "select_all", "split_selection_on_newline","goto_file", "goto_last_modified_file", ":buffer-close!", ":theme material_palenight"]
# esc = 'keep_primary_selection'

[keys.normal.space]
q = ":quit"

[keys.insert]
C-s = [":w!","normal_mode"]
C-w = [":buffer-close","normal_mode"]
C-v = [":clipboard-paste-before"]
A-right = "move_next_word_start"
A-left = "move_prev_word_start"
C-q = "collapse_selection"
C-space = "signature_help"
S-right = "extend_char_right"
S-left = "extend_char_left"
S-up = "extend_line_up"
S-down = "extend_line_down"
C-t = [":insert-output fzf-helix" ]
#


[keys.select]
# y = [":clipboard-yank","yank"]
X = ["extend_line_up", "extend_to_line_bounds"]
# if already in select mode, just add new selection at next occurrence
"C-d" = ["search_selection", "extend_search_next"]
";" = ["collapse_selection", "normal_mode"]
# Same behaviour as normal mode x
x = "extend_line"
# Counterpart for normal mode V
V = "extend_to_line_end"
A-right = "extend_next_word_start"
A-left = "extend_prev_word_start"
S-right = "extend_char_right"
S-left = "extend_char_left"
# esc = 'keep_primary_selection'
